### ISSUE TITLE
About this paper's code

### ISSUE THREAD

**Issue by sunskys** [Amal-Vincent/Gaze-estimation#1]
Hello, I recently studied in the eyes of estimation, I saw your thesis, can you send me a copy of your code, I want to learn, thank you, my e-mail is: ithusenbo@gmail.com

**Comment by Amal-Vincent** [comment]
I am afraid I am no longer affiliated with the University or the project, for try contacting Professor Krupa Jariwala, she should be able to help you, her email id is- knj@coed.svnit.ac.in

-Best
Amal
