### ISSUE TITLE
About this source code.

### ISSUE THREAD

**Issue by linjianing** [Amal-Vincent/Gaze-estimation#2]
Dear sir:
I recently read your paper about gaze estimation, and i am a graduate student doing gaze research too, so if i can ask for your source code. can you send me your source code via 931089023@qq.com.  If i use it, i will cite your paper in reference. Thanks so much~

**Comment by Amal-Vincent** [comment]
I am afraid I am no longer affiliated with the University or the project, for try contacting Professor Krupa Jariwala, she should be able to help you, her email id is- knj@coed.svnit.ac.in

-Best
Amal
