### ISSUE TITLE
Contact information

### ISSUE THREAD

**Issue by jgoenetxea** [Amal-Vincent/Gaze-estimation#3]
We are interested on the code of your method. It looks promising and we want to compare our approach with your implementation.
In the description of the repository you ask for a direct contact to talk about the source code of your work. However, there is not any contact information there. Can you provide an email address or any kind of contact information?

**Comment by Amal-Vincent** [comment]
I am afraid I am no longer affiliated with the University or the project, for try contacting Professor Krupa Jariwala, she should be able to help you, her email id is- knj@coed.svnit.ac.in

-Best
Amal
